### PR TITLE
clib: Add a reverse strstr function.

### PR DESCRIPTION
**Pull request by pnmanolova**
c_strrstr is a function that finds the last occurence of
string 'a' inside string 'b'. It's basically strstr in
reverse.

### CODE REVIEW

**Comment by rib** [comment]
thanks for this

I made some minor updates to your patch here:
https://github.com/rig-project/clib/commit/ec6852f7f02151f77e29f64d33e8b5f85c52fa14

Can you please let me know if the changes seem ok.

I added the c_return_if_fail debug checks to verify NULL pointers aren't passed in
I renamed the arguments to 'haystack' and 'needle' to be consistent with strstr
I removed the strlen of the haystack, since I think it's enough to know that for each iteration that strstr finds a match it's implicitly safe to move forward by the length of the needle.
minor coding style changes

**Comment by pnmanolova** [comment]
@rib Thank you for tidying up this patch! The changes you've made look perfectly fine to me. I'll include them in the LibRS clone too.

**Comment by pnmanolova** [comment]
@rib Something really pedantic, on second look I noticed you might have let some tabs slip. I removed them and updated this branch.

**Comment by rib** [comment]
Ah, yep, nasty tabs, thanks. I've pushed to master.

**Pull request closed without merging**
